# hello를 출력하는 도커 이미지 생성
# 1.베이스 이미지 명시
# FROM baseImage
FROM alpine

# 2.추가적으로 필요한 파일들을 다운로드. 현재는 너무 작은 기능을 가진 이미지라 이것이 따로 필요하지 않음.
# RUN command


# 3.컨테이너 시작 시 실행될 명령어 명시
# CMD ["executable"]
CMD ["echo", "hello"]